apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/logs  # 노드의 기본 디렉터리
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mnist-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/mnist
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/models  # 노드의 기본 디렉터리
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" 