apiVersion: v1
kind: Service
metadata:
  name: triton-server-service
spec:
  selector:
    app: triton-server
  ports:
  - name: http
    protocol: TCP
    port: 8000  # HTTP 포트
    targetPort: 8000
  - name: grpc
    protocol: TCP
    port: 8001  # gRPC 포트
    targetPort: 8001
  - name: metrics
    protocol: TCP
    port: 8002  # Metrics 포트
    targetPort: 8002
  type: ClusterIP
